// Auto-generated by scripts/generate_gallery.sh
// Do not edit by hand.

const galleryImages = [
  { src: "assets/images/IMG_3693.jpeg", alt: "Gallery image" },
  { src: "assets/images/IMG_3694.jpeg", alt: "Gallery image" },
  { src: "assets/images/IMG_3695.jpeg", alt: "Gallery image" },
  { src: "assets/images/IMG_3696.jpeg", alt: "Gallery image" },
  { src: "assets/images/IMG_3697.jpeg", alt: "Gallery image" },
  { src: "assets/images/IMG_3698.jpeg", alt: "Gallery image" },
  { src: "assets/images/IMG_3699.jpeg", alt: "Gallery image" },
  { src: "assets/images/IMG_3700.jpeg", alt: "Gallery image" },
  { src: "assets/images/IMG_3701.jpeg", alt: "Gallery image" },
  { src: "assets/images/IMG_3702.jpeg", alt: "Gallery image" },
  { src: "assets/images/IMG_3703.jpeg", alt: "Gallery image" },
  { src: "assets/images/IMG_3704.jpeg", alt: "Gallery image" },
  { src: "assets/images/IMG_3705.jpeg", alt: "Gallery image" },
  { src: "assets/images/IMG_3706.jpeg", alt: "Gallery image" }
];
