#!/usr/bin/env sh
set -e

IMAGES_DIR="assets/images"
OUT_FILE="gallery-data.js"

# Start file
cat > "$OUT_FILE" <<EOF
// Auto-generated by scripts/generate_gallery.sh
// Do not edit by hand.

const galleryImages = [
EOF

first=1

# Loop over common image extensions
for ext in jpg jpeg png gif webp; do
  for img in "$IMAGES_DIR"/*."$ext"; do
    [ -e "$img" ] || continue  # skip if no files for this ext

    # Strip leading ./ if present
    rel_path="$img"
    case "$rel_path" in
      ./*) rel_path="${rel_path#./}" ;;
    esac

    if [ $first -eq 0 ]; then
      printf ',\n' >> "$OUT_FILE"
    fi
    first=0

    # Simple JSON-ish object; no captions
    printf '  { src: "%s", alt: "Gallery image" }' "$rel_path" >> "$OUT_FILE"
  done
done

# Close array
printf '\n];\n' >> "$OUT_FILE"

echo "Wrote $OUT_FILE"
